# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: oracle_enhanced
  host: 172.30.94.177
  port: 1521
  database: gfip
  username: pagos_fipa
  password: pagos
  pool: 5

production:
  adapter: oracle_enhanced
  host: 172.30.94.177
  port: 1521
  database: gfip
  username: pagos_fipa
  password: pagos
  pool: 50
